Diplom: ContainerPreparer< T > Class Template Reference
ContainerPreparer< T > Class Template Reference
Used to generate vector of container's functions. This class was created, to reduce delays while accessing functions from container under test.
#include <ContainerPreparer.h>
Public Member Functions
ContainerPreparer (sequence::AvailableFunctions availableFunctions)
Constructor for class.
const std::vector< std::function< void(T &, int, int)> > & getFuncPtrs () const
returns prepared vector of container's operations
virtual void init ()
is used to initialize vector of functions
Private Attributes
sequence::AvailableFunctions availableFunctions
is used to check if the container under test has methods
std::vector< std::function< void(T &, int, int)> > func_ptrs
vector of container's functions
Detailed Description
template<class T>
class ContainerPreparer< T >
Used to generate vector of container's functions. This class was created, to reduce delays while accessing functions from container under test.
Definition at line 18 of file ContainerPreparer.h.
Constructor & Destructor Documentation
ContainerPreparer()
template<class T > ContainerPreparer< T >::ContainerPreparer (sequence::AvailableFunctions availableFunctions) explicit
Constructor for class.
Parameters
availableFunctions is used to check if the container under test has methods
Definition at line 85 of file ContainerPreparer.h.
Member Function Documentation
getFuncPtrs()
template<class T > const std::vector< std::function< void(T &, int, int)> > & ContainerPreparer< T >::getFuncPtrs
returns prepared vector of container's operations
Definition at line 95 of file ContainerPreparer.h.
init()
template<class T > void ContainerPreparer< T >::init virtual
is used to initialize vector of functions
Definition at line 48 of file ContainerPreparer.h.
References sequence::hasAccessElement(), sequence::hasDeleteFront(), sequence::hasDeleteIndexed(), sequence::hasEmplace(), sequence::hasInsertBack(), sequence::hasInsertFront(), and sequence::hasInsertIndexed().
Member Data Documentation
availableFunctions
template<class T > sequence::AvailableFunctions ContainerPreparer< T >::availableFunctions private
is used to check if the container under test has methods
Definition at line 44 of file ContainerPreparer.h.
func_ptrs
template<class T > std::vector<std::function<void(T &, int, int)> > ContainerPreparer< T >::func_ptrs private
vector of container's functions
Definition at line 40 of file ContainerPreparer.h.
The documentation for this class was generated from the following file:
/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/operations/ContainerPreparer.h