Diplom: sequence Namespace Reference
sequence Namespace Reference
Concepts
concept AvailableFunctionsType
Used to check if value is a part of enum.
Enumerations
enum AvailableFunctions : uint32_t {
INSERT_FRONT = 0x0000'0001 , INSERT_BACK = 0x0000'0010 , INSERT_INDEXED = 0x0000'0100 , ACCESS_ELEMENT = 0x0000'1000 ,
EMPLACE = 0x0001'0000 , DELETE_FRONT = 0x0010'0000 , DELETE_BACK = 0x0100'0000 , DELETE_INDEXED = 0x1000'0000
}
Functions
always_inline AvailableFunctions addAccessElementOperation (AvailableFunctions availableFunctions)
add ACCESS_ELEMENT operation to original value
always_inline AvailableFunctions addAllOperations (AvailableFunctions availableFunctions)
add INSERT_FRONT, INSERT_BACK, INSERT_INDEXED, ACCESS_ELEMENT, EMPLACE, DELETE_FRONT, DELETE_INDEXED, DELETE_BACK operations to original value
always_inline AvailableFunctions addDeleteBackOperation (AvailableFunctions availableFunctions)
add DELETE_BACK operation to original value
always_inline AvailableFunctions addDeleteFrontOperation (AvailableFunctions availableFunctions)
add DELETE_FRONT operation to original value
always_inline AvailableFunctions addDeleteIndexedOperation (AvailableFunctions availableFunctions)
add DELETE_INDEXED operation to original value
always_inline AvailableFunctions addEmplaceOperation (AvailableFunctions availableFunctions)
add EMPLACE operation to original value
always_inline AvailableFunctions addInsertBackOperation (AvailableFunctions availableFunctions)
add INSERT_BACK operation to original value
always_inline AvailableFunctions addInsertFrontOperation (AvailableFunctions availableFunctions)
add INSERT_FRONT operation to original value
always_inline AvailableFunctions addInsertIndexedOperation (AvailableFunctions availableFunctions)
add INSERT_INDEXED operation to original value
always_inline bool hasAccessElement (AvailableFunctions availableFunctions)
check ACCESS_ELEMENT operation for availability
always_inline bool hasDeleteBack (AvailableFunctions availableFunctions)
check DELETE_BACK operation for availability
always_inline bool hasDeleteFront (AvailableFunctions availableFunctions)
check DELETE_FRONT operation for availability
always_inline bool hasDeleteIndexed (AvailableFunctions availableFunctions)
check DELETE_INDEXED operation for availability
always_inline bool hasEmplace (AvailableFunctions availableFunctions)
check EMPLACE operation for availability
always_inline bool hasInsertBack (AvailableFunctions availableFunctions)
check INSERT_BACK operation for availability
always_inline bool hasInsertFront (AvailableFunctions availableFunctions)
check INSERT_FRONT operation for availability
always_inline bool hasInsertIndexed (AvailableFunctions availableFunctions)
check INSERT_INDEXED operation for availability
template<AvailableFunctionsType T>
always_inline bool hasOperation (AvailableFunctions availableFunctions, T valueToCheck)
check provided operation for availability
always_inline AvailableFunctions setOperation (AvailableFunctions availableFunctions, AvailableFunctions valueToSet)
set provided operation to original value
Enumeration Type Documentation
AvailableFunctions
enum sequence::AvailableFunctions : uint32_t
Enumerator
INSERT_FRONT
INSERT_BACK
INSERT_FRONT corresponds to insertion operations at the beginning.
INSERT_INDEXED
INSERT_BACK corresponds to insertion operations at the end.
ACCESS_ELEMENT
INSERT_INDEXED corresponds to insertion operations by index.
EMPLACE
ACCESS_ELEMENT corresponds to access operations to the element.
DELETE_FRONT
EMPLACE corresponds to the operations of on-site construction of the element.
DELETE_BACK
DELETE_FRONT corresponds to deletion operations from the beginning.
DELETE_INDEXED
DELETE_BACK corresponds to end deletion operations.
Definition at line 29 of file ContainerFunctions.h.
Function Documentation
addAccessElementOperation()
always_inline AvailableFunctions sequence::addAccessElementOperation (AvailableFunctions availableFunctions)
add ACCESS_ELEMENT operation to original value
Parameters
availableFunctions original value
Definition at line 66 of file ContainerFunctions.h.
References ACCESS_ELEMENT.
addAllOperations()
always_inline AvailableFunctions sequence::addAllOperations (AvailableFunctions availableFunctions)
add INSERT_FRONT, INSERT_BACK, INSERT_INDEXED, ACCESS_ELEMENT, EMPLACE, DELETE_FRONT, DELETE_INDEXED, DELETE_BACK operations to original value
Parameters
availableFunctions original value
Definition at line 102 of file ContainerFunctions.h.
References ACCESS_ELEMENT, DELETE_BACK, DELETE_FRONT, DELETE_INDEXED, EMPLACE, INSERT_BACK, INSERT_FRONT, and INSERT_INDEXED.
addDeleteBackOperation()
always_inline AvailableFunctions sequence::addDeleteBackOperation (AvailableFunctions availableFunctions)
add DELETE_BACK operation to original value
Parameters
availableFunctions original value
Definition at line 94 of file ContainerFunctions.h.
References DELETE_BACK.
addDeleteFrontOperation()
always_inline AvailableFunctions sequence::addDeleteFrontOperation (AvailableFunctions availableFunctions)
add DELETE_FRONT operation to original value
Parameters
availableFunctions original value
Definition at line 80 of file ContainerFunctions.h.
References DELETE_FRONT.
addDeleteIndexedOperation()
always_inline AvailableFunctions sequence::addDeleteIndexedOperation (AvailableFunctions availableFunctions)
add DELETE_INDEXED operation to original value
Parameters
availableFunctions original value
Definition at line 87 of file ContainerFunctions.h.
References DELETE_INDEXED.
addEmplaceOperation()
always_inline AvailableFunctions sequence::addEmplaceOperation (AvailableFunctions availableFunctions)
add EMPLACE operation to original value
Parameters
availableFunctions original value
Definition at line 73 of file ContainerFunctions.h.
References EMPLACE.
addInsertBackOperation()
always_inline AvailableFunctions sequence::addInsertBackOperation (AvailableFunctions availableFunctions)
add INSERT_BACK operation to original value
Parameters
availableFunctions original value
Definition at line 52 of file ContainerFunctions.h.
References INSERT_BACK.
addInsertFrontOperation()
always_inline AvailableFunctions sequence::addInsertFrontOperation (AvailableFunctions availableFunctions)
add INSERT_FRONT operation to original value
Parameters
availableFunctions original value
Definition at line 44 of file ContainerFunctions.h.
References INSERT_FRONT.
addInsertIndexedOperation()
always_inline AvailableFunctions sequence::addInsertIndexedOperation (AvailableFunctions availableFunctions)
add INSERT_INDEXED operation to original value
Parameters
availableFunctions original value
Definition at line 59 of file ContainerFunctions.h.
References INSERT_INDEXED.
hasAccessElement()
always_inline bool sequence::hasAccessElement (AvailableFunctions availableFunctions)
check ACCESS_ELEMENT operation for availability
Parameters
availableFunctions original value
Definition at line 147 of file ContainerFunctions.h.
References ACCESS_ELEMENT.
Referenced by ContainerPreparer< T >::init().
hasDeleteBack()
always_inline bool sequence::hasDeleteBack (AvailableFunctions availableFunctions)
check DELETE_BACK operation for availability
Parameters
availableFunctions original value
Definition at line 175 of file ContainerFunctions.h.
References DELETE_BACK.
hasDeleteFront()
always_inline bool sequence::hasDeleteFront (AvailableFunctions availableFunctions)
check DELETE_FRONT operation for availability
Parameters
availableFunctions original value
Definition at line 161 of file ContainerFunctions.h.
References DELETE_FRONT.
Referenced by ContainerPreparer< T >::init().
hasDeleteIndexed()
always_inline bool sequence::hasDeleteIndexed (AvailableFunctions availableFunctions)
check DELETE_INDEXED operation for availability
Parameters
availableFunctions original value
Definition at line 168 of file ContainerFunctions.h.
References DELETE_INDEXED.
Referenced by ContainerPreparer< T >::init().
hasEmplace()
always_inline bool sequence::hasEmplace (AvailableFunctions availableFunctions)
check EMPLACE operation for availability
Parameters
availableFunctions original value
Definition at line 154 of file ContainerFunctions.h.
References EMPLACE.
Referenced by ContainerPreparer< T >::init().
hasInsertBack()
always_inline bool sequence::hasInsertBack (AvailableFunctions availableFunctions)
check INSERT_BACK operation for availability
Parameters
availableFunctions original value
Definition at line 133 of file ContainerFunctions.h.
References INSERT_BACK.
Referenced by ContainerPreparer< T >::init().
hasInsertFront()
always_inline bool sequence::hasInsertFront (AvailableFunctions availableFunctions)
check INSERT_FRONT operation for availability
Parameters
availableFunctions original value
Definition at line 126 of file ContainerFunctions.h.
References INSERT_FRONT.
Referenced by ContainerPreparer< T >::init().
hasInsertIndexed()
always_inline bool sequence::hasInsertIndexed (AvailableFunctions availableFunctions)
check INSERT_INDEXED operation for availability
Parameters
availableFunctions original value
Definition at line 140 of file ContainerFunctions.h.
References INSERT_INDEXED.
Referenced by ContainerPreparer< T >::init().
hasOperation()
template<AvailableFunctionsType T> always_inline bool sequence::hasOperation (AvailableFunctions availableFunctions, T valueToCheck)
check provided operation for availability
Parameters
availableFunctions original value
valueToCheck value is checking for
Template Parameters
T used to check if provided value is a part of AvailableFunctions enum
Definition at line 185 of file ContainerFunctions.h.
setOperation()
always_inline AvailableFunctions sequence::setOperation (AvailableFunctions availableFunctions, AvailableFunctions valueToSet)
set provided operation to original value
Parameters
availableFunctions original value
valueToSet value which will be set
Definition at line 119 of file ContainerFunctions.h.