.TH "/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/cmake-build-debug/CMakeFiles/3.26.4 Directory Reference" 3 "Sat Sep 30 2023" "Diplom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/cmake-build-debug/CMakeFiles/3.26.4 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCompilerIdCXX\fP"
.br
.in -1c
