.TH "/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/DurationCounter.h" 3 "Sat Sep 30 2023" "Diplom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/DurationCounter.h
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include 'iostream'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasicDurationCounter\fP"
.br
.RI "Start time counting after initialization\&. "
.ti -1c
.RI "class \fBLogDuration\fP"
.br
.RI "Prints total elapsed time while destructor called in ms\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Diplom from the source code\&.
