.TH "/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/main.cpp" 3 "Sat Sep 30 2023" "Diplom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'PRNG\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB4\fP of file \fBmain\&.cpp\fP\&.
.PP
References \fBPRNG::generateNumber64()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diplom from the source code\&.
