.TH "MapTester< T >" 3 "Sat Sep 30 2023" "Diplom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapTester< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ContainerTest\&.h>\fP
.PP
Inherits \fBContainerTest< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapTester\fP (T &&\fBcontainer\fP)"
.br
.ti -1c
.RI "uint64_t \fBtest\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBContainerTest< T >\fP
.in +1c
.ti -1c
.RI "\fBContainerTest\fP (T &&testing_container)"
.br
.ti -1c
.RI "virtual uint64_t \fBtest\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class MapTester< T >"
.PP
Definition at line \fB38\fP of file \fBContainerTest\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBMapTester\fP< T >\fB::MapTester\fP (T && container)\fC [explicit]\fP"

.PP
Definition at line \fB16\fP of file \fBContainerTest\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > uint64_t \fBMapTester\fP< T >::test ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBContainerTest< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Diplom from the source code\&.
