.TH "PRNG" 3 "Sat Sep 30 2023" "Diplom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PRNG \- Pseudo-random number generator\&. Provides interface to generate numbers: 32, 64 bit\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PRNG\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int32_t \fBgenerateNumber32\fP (int min=INT32_MIN, int max=INT32_MAX)"
.br
.RI "generateNumber32 returns random 32-bit number "
.ti -1c
.RI "int64_t \fBgenerateNumber64\fP (int64_t min=INT64_MIN, int64_t max=INT64_MAX)"
.br
.RI "generateNumber64 returns random 64-bit number "
.ti -1c
.RI "int64_t \fBgetSeed\fP () const"
.br
.RI "getSeed - getter for seed "
.ti -1c
.RI "\fBPRNG\fP ()"
.br
.ti -1c
.RI "\fBPRNG\fP (int64_t userSeed)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::mt19937 \fBgen32\fP"
.br
.ti -1c
.RI "std::mt19937_64 \fBgen64\fP"
.br
.ti -1c
.RI "std::unique_ptr< int64_t > \fBseed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pseudo-random number generator\&. Provides interface to generate numbers: 32, 64 bit\&. 


.PP
\fBParameters\fP
.RS 4
\fIseed\fP pointer to \fBint64_t\fP which is used for generating random numbers 
.br
\fIgen32\fP Mersenne twister 32-bit number generator 
.br
\fIgen64\fP Mersenne twister 64-bit number generator 
.RE
.PP

.PP
Definition at line \fB17\fP of file \fBPRNG\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PRNG::PRNG ()\fC [explicit]\fP"

.PP
Definition at line \fB20\fP of file \fBPRNG\&.cpp\fP\&.
.PP
References \fBgen32\fP, and \fBgen64\fP\&.
.SS "PRNG::PRNG (int64_t userSeed)\fC [explicit]\fP"

.PP
Definition at line \fB7\fP of file \fBPRNG\&.cpp\fP\&.
.PP
References \fBgen32\fP, \fBgen64\fP, and \fBseed\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int32_t PRNG::generateNumber32 (int min = \fCINT32_MIN\fP, int max = \fCINT32_MAX\fP)"

.PP
generateNumber32 returns random 32-bit number 
.PP
\fBParameters\fP
.RS 4
\fImin\fP - lower limit of the generator 
.br
\fImax\fP - upper limit of the generator 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBPRNG\&.cpp\fP\&.
.PP
References \fBgen32\fP\&.
.SS "int64_t PRNG::generateNumber64 (int64_t min = \fCINT64_MIN\fP, int64_t max = \fCINT64_MAX\fP)"

.PP
generateNumber64 returns random 64-bit number 
.PP
\fBParameters\fP
.RS 4
\fImin\fP - lower limit of the generator 
.br
\fImax\fP - upper limit of the generator 
.RE
.PP

.PP
Definition at line \fB31\fP of file \fBPRNG\&.cpp\fP\&.
.PP
References \fBgen64\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "int64_t PRNG::getSeed () const"

.PP
getSeed - getter for seed 
.PP
Definition at line \fB13\fP of file \fBPRNG\&.cpp\fP\&.
.PP
References \fBseed\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::mt19937 PRNG::gen32\fC [protected]\fP"

.PP
Definition at line \fB40\fP of file \fBPRNG\&.h\fP\&.
.PP
Referenced by \fBgenerateNumber32()\fP, and \fBPRNG()\fP\&.
.SS "std::mt19937_64 PRNG::gen64\fC [protected]\fP"

.PP
Definition at line \fB41\fP of file \fBPRNG\&.h\fP\&.
.PP
Referenced by \fBgenerateNumber64()\fP, and \fBPRNG()\fP\&.
.SS "std::unique_ptr<int64_t> PRNG::seed\fC [protected]\fP"

.PP
Definition at line \fB39\fP of file \fBPRNG\&.h\fP\&.
.PP
Referenced by \fBgetSeed()\fP, and \fBPRNG()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Diplom from the source code\&.
