.TH "/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/PRNG.h" 3 "Sat Sep 30 2023" "Diplom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/PRNG.h
.SH SYNOPSIS
.br
.PP
\fC#include <random>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPRNG\fP"
.br
.RI "Pseudo-random number generator\&. Provides interface to generate numbers: 32, 64 bit\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Diplom from the source code\&.
