.TH "/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/TestOperations.h" 3 "Sat Sep 30 2023" "Diplom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kirillzhukov/Documents/GitHub/Diplom/diplom/TestOperations.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSequenceOperations\fP : unsigned char { \fBINSERT_FRONT\fP, \fBINSERT_BACK\fP, \fBINSERT_INDEXED\fP, \fBACCESS_ELEMENT\fP, \fBEMPLACE\fP, \fBDELETE_FRONT\fP, \fBDELETE_INDEXED\fP, \fBDELETE_BACK\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSequenceOperations\fP : unsigned char"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINSERT_FRONT \fP\fP
.TP
\fB\fIINSERT_BACK \fP\fP
.TP
\fB\fIINSERT_INDEXED \fP\fP
.TP
\fB\fIACCESS_ELEMENT \fP\fP
.TP
\fB\fIEMPLACE \fP\fP
.TP
\fB\fIDELETE_FRONT \fP\fP
.TP
\fB\fIDELETE_INDEXED \fP\fP
.TP
\fB\fIDELETE_BACK \fP\fP
.PP
Definition at line \fB8\fP of file \fBTestOperations\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diplom from the source code\&.
